version: "3.7"
services:
  app:
    build:
      args:
        user: laravel
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    image: set-server
    container_name: set-server-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - set-server

  db:
    image: mysql:8.0
    container_name: set-server-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - set-server

  nginx:
    image: nginx:latest
    container_name: set-server-nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - set-server

networks:
  set-server:
    driver: bridge